import pandas as pd

# Read the pangenome table generated by Roary
df = pd.read_csv("gene_presence_absence.csv")

# Filter genes that are present in both Bacteria_A and Bacteria_B (Core Genes / Orthologs)
core_genes = df[(df['Bacteria_A'].notnull()) & (df['Bacteria_B'].notnull())]
print(f"Total core genes found: {len(core_genes)}")

# Find genes that are uniquely present in Bacteria_A (not in Bacteria_B)
# (e.g., potential virulence factors or antibiotic resistance genes)
unique_to_A_genes = df[(df['Bacteria_A'].notnull()) & (df['Bacteria_B'].isnull())]
print("\nList of unique genes in Bacteria A:")
print(unique_to_A_genes['Gene'].head()) # Display the first 5 genes